// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xOGch2-KX4E93eXUl07DBnnR0X5TSos',
    appId: '1:931965156716:web:492eb91c763badcc39c749',
    messagingSenderId: '931965156716',
    projectId: 'codesthinkers-41602',
    authDomain: 'codesthinkers-41602.firebaseapp.com',
    storageBucket: 'codesthinkers-41602.appspot.com',
    measurementId: 'G-H9EEQ2Q0QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjNjThABng4GqGvmE3SuracbOk6DJraJA',
    appId: '1:931965156716:android:53de9f82545560d739c749',
    messagingSenderId: '931965156716',
    projectId: 'codesthinkers-41602',
    storageBucket: 'codesthinkers-41602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhgboLbpnKCbzLbK9LL4k64bdEhW41FI4',
    appId: '1:931965156716:ios:17a15c3ec7f3e57e39c749',
    messagingSenderId: '931965156716',
    projectId: 'codesthinkers-41602',
    storageBucket: 'codesthinkers-41602.appspot.com',
    iosBundleId: 'com.example.codesThinkers',
  );
}
